# Generated by Django 3.1.3 on 2020-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
